---
id: e4c60f99-9edb-4df8-a41b-a24eee086ee3
name: qa-rc2
values:
## Domain url of MOSIP installation
- key: url
  value: https://qa4.mosip.net
  enabled: true
## MOSIP provided policy group.
- key: policygroupname
  value: policygroup115
  enabled: true
## MOSIP provided policy 
- key: policyname
  value: policy115
  enabled: true
## Provided by partner
- key: partnerid
  value: authpartner115
  enabled: true
## Keycloak base url  
- key: kcurl
  value: https://qa4.mosip.net/
  enabled: true
## Keycloak admin user name 
- key: kcusername
  value: admin
  enabled: true
## Keycloak admin password
- key: kcpassword
  value: admin
  enabled: true
## DO NOT CHANGE 
- key: applicationid
  value: partner
  enabled: true
## MOSIP provided mosip-partner-client secret   
- key: clientsecret
  value: abc123
  enabled: true

## Partner user name
- key: username
  value: '110068'
  enabled: true
## Partner password
- key: password
  value: Techno@123
  enabled: true
- key: partneremail
  value: partnerdemoemail115@mail.com
  enabled: true
- key: partnerpassword
  value: admin
  enabled: true
- key: partneraddress
  value: address,ogpartner
  enabled: true
- key: partnercontact
  value: '9898989115'
  enabled: true

## One time MISP partner (onboarded by Admin)
- key: MISPcontact
  value: '9898989115'
  enabled: true
- key: MISPpartneremail
  value: demomispemail115@mail.com
  enabled: true
- key: MISPpartnerid
  value: MISPpartner115
  enabled: true
- key: MISPaddress
  value: demo address,country 1,earth
  enabled: true

## Used by all APIs
- key: requesttime
  value: ''
  enabled: true

## Keys to store API responses. No values required to be filled here.
- key: policygroupid
  value: ''
  enabled: true
- key: policyid
  value: ''
  enabled: true
- key: kcuserid
  value: ''
  enabled: true
- key: kcroleid
  value: ''
  enabled: true
- key: apikey
  value: ''
  enabled: true

## MOSIP provided datashare policy 
- key: datasharepolicyname
  value: datasharepolicy2
  enabled: true
- key: datasharepolicygroupname
  value: datasharepolicygroup2
  enabled: true

## Keys to store API responses. No values required to be filled here.
- key: datasharepolicyid
  value: '' 
  enabled: true
- key: datasharepolicygroupid
  value: '' 
  type: any
  enabled: true
- key: misplicensekey
  value: ''
  enabled: true

## MOSIP provided unique label for API key generation. Should be unique across all Auth Partners.
- key: label
  value: label115
  enabled: true

_postman_variable_scope: environment
_postman_exported_at: '2022-01-31T11:00:44.335Z'
_postman_exported_using: Postman/8.12.5
