apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}

data:
  maven-metadata.xml: |-
    <metadata>
      <groupId>io.mosip.registration</groupId>
      <artifactId>registration-services</artifactId>
      <versioning>
        <versions>
           <version>{{ .Values.regclient.version }}</version>
        </versions>
      <lastUpdated>20200729125958</lastUpdated>
      </versioning>
    </metadata>

  logback.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>

    	<property name="LOG_PATTERN" value="%d %p [%t] %c{5} : %m%n" />
    	<property name="APP_LOG_ROOT" value="logs"/>

    	<appender name="applicationLog" class="ch.qos.logback.core.rolling.RollingFileAppender">
    		<file>${APP_LOG_ROOT}/registration.log</file>
    		<encoder>
    			<pattern>${LOG_PATTERN}</pattern>
    		</encoder>
    		<rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
    			<fileNamePattern>${APP_LOG_ROOT}/registration-%i.log</fileNamePattern>
    			<minIndex>1</minIndex>
    			<maxIndex>10</maxIndex>
    		</rollingPolicy>
    		<triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
    			<maxFileSize>10MB</maxFileSize>
    		</triggeringPolicy>
    	</appender>

    	<appender name="metrics" class="ch.qos.logback.core.rolling.RollingFileAppender">
    		<file>${APP_LOG_ROOT}/metrics.log</file>
    		<encoder class="net.logstash.logback.encoder.LogstashEncoder"/>
    		<rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
    			<fileNamePattern>${APP_LOG_ROOT}/metrics-archive.%d{yyyy-MM-dd_HH}.log</fileNamePattern>
    		</rollingPolicy>
    	</appender>

    	<logger name="io.mosip" level="INFO" additivity="false">
    		<appender-ref ref="applicationLog" />
    	</logger>

    	<logger name="io.mosip.registration.config.LoggingJsonMeterRegistry" level="INFO" additivity="false">
    		<appender-ref ref="metrics" />
    	</logger>

    </configuration>