{{ if .Values.kafkaClient.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
spec:
  containers:
  - name: kafka-client
    image: {{ .Values.kafkaClient.image }}
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
    {{ if .Values.kafkaClient.db_secretref }}
    env:
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: {{ .Values.kafkaClient.db_secretref.name }}
          key: {{ .Values.kafkaClient.db_secretref.key }}
    {{ end }}
{{ end }}
